version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.43
      KAFKA_LOG_CLEANER_ENABLE: 'true'
      KAFKA_LOG_CLEANER_POLICY: 'delete'
      KAFKA_LOG_RETENTION_HOURS: 4
      KAFKA_LOG_RETENTION_BYTES: 536870912
      KAFKA_LOG_SEGMENT_BYTES: 536870912
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 120000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
